version: '3.7'
services:
#  sds-app:
#    build: .
#    ports:
#      - 8080:8080
#      - 8081:8081
#    depends_on:
#      - sds-mysql
#    restart: always
  sds-mysql:
    image: mysql:5.7.23
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: sds
    ports:
      - 3306:3306
    restart: always
