version: '3.7'
services:
  app:
    build: .
    depends_on:
      - mysql
    restart: always
  mysql:
    image: mysql:5.7.23
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: sds
    ports:
      - 3306:3306
    #    volumes:
    #      - ../data/keycloak:/var/lib/mysql
    restart: always
